---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: natscustom
          imagePullPolicy: Never
          ports:
            - name: wssport
              containerPort: 9090
            - name: clientport
              containerPort: 4222
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  selector:
    app: nats
  type: NodePort
  ports:
    - name: client
      port: 4222
      targetPort: 4222
      protocol: TCP
      nodePort: 30022
    - name: wss
      port: 9090
      targetPort: 9090
      protocol: TCP
      nodePort: 30090
---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: natsfeapp
          imagePullPolicy: Never
          ports:
            - name: wssport
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - name: client
      port: 30030
      targetPort: 30030
      protocol: TCP
      nodePort: 30030
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: natsbeapp
          imagePullPolicy: Never
          ports:
            - name: api
              containerPort: 1234
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - name: client
      port: 1234
      targetPort: 1234
      protocol: TCP
      nodePort: 30034